import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import styles from "/styles/layout.module.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Set the opacity class based on the current pathname
  const pathname =
    typeof window !== "undefined" ? window.location.pathname : "/"; // Default to root for server-side
  const opacityClass = pathname === "/" ? "" : styles.otherBackground; // Apply otherBackground class for routes other than "/"
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${opacityClass}`}
        style={{ backgroundImage: "var(--background-image)" }} // Apply the common background image
      >
        {children}
      </body>
    </html>
  );
}
