import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";
import styles from "./styles/layout.module.css";
import Footer from "./components/footer";
import Navbar from "./components/navbar";
import ScrollHandler from "./components/ScrollHandler";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/*  <ScrollHandler /> */}
        <Navbar />
        {/* For styles in globals.css, you don't use styles. You just use the regular class names directly (e.g., className="heroSection"). */}
        <section className={styles.heroSection}></section>

        {/* For styles in layout.module.css, you use styles because those class names are scoped locally to the component (e.g., className={styles.heroSection}). */}
        <main className={`${styles.mainContent} flex-grow pt-20`}>
          {children}
        </main>

        <footer>
          {" "}
          <Footer />
        </footer>
      </body>
    </html>
  );
}
